import { CustomersTable } from "@/components/customers-table"

export const mockCustomers = [
  {
    id: "1",
    firstName: "Богдан",
    lastName: "Адмін",
    role: "ADMIN",
    status: "ACTIVE",
    username: "bohdan_dev",
    phone: "+380971234567",
  },
  {
    id: "2",
    firstName: "Олена",
    lastName: "Коваль",
    role: "USER",
    status: "NEW",
    username: "olena_k",
    phone: "+380631112233",
  },
  {
    id: "3",
    firstName: "Дмитро",
    lastName: "Петренко",
    role: "MANAGER",
    status: "ACTIVE",
    username: "dima_ptr",
    phone: "+380504445566",
  },
  {
    id: "4",
    firstName: "Марія",
    lastName: "Шевченко",
    role: "USER",
    status: "BANNED",
    username: "mary_shev",
    phone: null,
  },
  {
    id: "5",
    firstName: "Артем",
    lastName: "Іванов",
    role: "USER",
    status: "COMPLETED",
    username: "art_ivan",
    phone: "+380677778899",
  },
  {
    id: "6",
    firstName: "Юлія",
    lastName: "Мельник",
    role: "MANAGER",
    status: "ACTIVE",
    username: "july_mel",
    phone: "+380931234500",
  },
  {
    id: "7",
    firstName: "Сергій",
    lastName: "Ткаченко",
    role: "USER",
    status: "NEW",
    username: "serg_tk",
    phone: "+380956667788",
  },
  {
    id: "8",
    firstName: "Анна",
    lastName: "Бондар",
    role: "USER",
    status: "ACTIVE",
    username: "ann_bond",
    phone: "+380682223344",
  },
  {
    id: "9",
    firstName: "Віталій",
    lastName: "Лисенко",
    role: "ADMIN",
    status: "ACTIVE",
    username: "vital_lys",
    phone: "+380993334455",
  },
  {
    id: "10",
    firstName: "Оксана",
    lastName: "Павленко",
    role: "USER",
    status: "COMPLETED",
    username: "ksana_p",
    phone: null,
  },
  {
    id: "11",
    firstName: "Іван",
    lastName: "Кравченко",
    role: "MANAGER",
    status: "ACTIVE",
    username: "ivan_krav",
    phone: "+380665554433",
  },
  {
    id: "12",
    firstName: "Ольга",
    lastName: "Савченко",
    role: "USER",
    status: "BANNED",
    username: "olga_sav",
    phone: "+380970001122",
  },
  {
    id: "13",
    firstName: "Максим",
    lastName: "Козак",
    role: "USER",
    status: "NEW",
    username: "max_kozak",
    phone: "+380638889900",
  },
  {
    id: "14",
    firstName: "Тетяна",
    lastName: "Мороз",
    role: "USER",
    status: "ACTIVE",
    username: "tany_moroz",
    phone: "+380501239876",
  },
  {
    id: "15",
    firstName: "Андрій",
    lastName: "Кузьменко",
    role: "MANAGER",
    status: "COMPLETED",
    username: "andrew_kuz",
    phone: "+380671110022",
  },
  {
    id: "16",
    firstName: "Світлана",
    lastName: "Зайцева",
    role: "USER",
    status: "NEW",
    username: "sveta_zay",
    phone: null,
  },
  {
    id: "17",
    firstName: "Руслан",
    lastName: "Гончар",
    role: "USER",
    status: "ACTIVE",
    username: "rus_gonchar",
    phone: "+380934445566",
  },
  {
    id: "18",
    firstName: "Наталія",
    lastName: "Клименко",
    role: "ADMIN",
    status: "ACTIVE",
    username: "nat_klym",
    phone: "+380957778811",
  },
  {
    id: "19",
    firstName: "Денис",
    lastName: "Олійник",
    role: "USER",
    status: "COMPLETED",
    username: "den_olyn",
    phone: "+380683332211",
  },
  {
    id: "20",
    firstName: "Вікторія",
    lastName: "Король",
    role: "USER",
    status: "ACTIVE",
    username: "vicky_k",
    phone: "+380991112233",
  },
  {
    id: "21",
    firstName: "Олександр",
    lastName: "Чумак",
    role: "MANAGER",
    status: "BANNED",
    username: "alex_chum",
    phone: "+380661234567",
  },
  {
    id: "22",
    firstName: "Валентина",
    lastName: "Білоус",
    role: "USER",
    status: "NEW",
    username: "valya_b",
    phone: null,
  },
  {
    id: "23",
    firstName: "Євген",
    lastName: "Колос",
    role: "USER",
    status: "ACTIVE",
    username: "evgen_kolos",
    phone: "+380975556677",
  },
  {
    id: "24",
    firstName: "Ірина",
    lastName: "Терещенко",
    role: "MANAGER",
    status: "ACTIVE",
    username: "ira_ter",
    phone: "+380632221100",
  },
  {
    id: "25",
    firstName: "Микола",
    lastName: "Дяченко",
    role: "USER",
    status: "COMPLETED",
    username: "nick_dya",
    phone: "+380509990011",
  },
]

export default async function CustomersPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight">Клієнти</h1>
      </div>
      <CustomersTable initialData={mockCustomers} />
    </div>
  )
}